### ISSUE TITLE
Enable multiple plugins in one repo to be documented

### ISSUE THREAD

**Issue by andrewvc** [elastic/docs-tools#11]
We are moving the ES input/output/filter into one repo here: https://github.com/logstash-plugins/logstash-integration-elasticsearch/pull/3

We need to update our docs tools to pull in multiple docs from one repo.

What is the easiest way to enable that?

**Comment by jordansissel** [comment]
This depends.

* Are we doing a universal plugin that provides an input, filter, and output?
* Or are we doing some hack to just have 3 plugins in 1 repo, with 3 gemspecs, etc?

I would prefer *only* universal plugins are targeted, because that is the future of plugins in Logstash.

That said, today we have this (background):

`docs/index.asciidoc` in one repo per plugin

For this to work for a universal plugin, we need a way for a universal plugin to tell the docs generator what documentation it has.

----

So: we need:

1) A way for a universal plugin to describe (programmatically? via yaml file?) the functionality it provides (input names, filter names, etc)
2) Then the docs to be written for each thing in the `docs/` directory.

Once we have a protocol figured out, we can update the tooling to use this protocol.

**Comment by karenzone** [comment]
@jsvd We have this functionality now with integration plugins. Can you think of a use case outside of integrations, or can we close this one as fixed?

**Comment by jsvd** [comment]
done done! good job :)
