### ISSUE TITLE
Include plugin documentation in Logstash docs sync tool

### ISSUE THREAD

**Issue by jordansissel** [elastic/docs-tools#3]
Reference: https://github.com/elastic/logstash/issues/6846

**Comment by jordansissel** [comment]
cc @ph

**Comment by ph** [comment]
@jordansissel 
I'll make a script that generate a JSON document with the following format:

```json
{
 "logtash-input-beats", "1.5.4",
 "logtash-input-file", "1.7.7",
 "logtash-codec-json", "1.8.7",
}

**Comment by ph** [comment]
@jordansissel Your idea is working way better than expected, I've been able to successfully do a graph resolution without installing the plugin, all that bundler/x-pack yak shaving pays off.

See this [gist](https://gist.github.com/ph/710072646bfc525fc8431d18f8c67fa1) for an example output.

Also that logic will make sure that the version of the default plugins shipper with the current branch, will have higher priority over the other version when generating the doc, this is to make sure that we don't update something we don't want.

The process is a bit slow, since I do a resolution each time I add a non default plugin, but this is also the safest. I could probably optimize that and do a few plugins at a time.

I will also changes the structure of the proposed json to include errors.

**Comment by ph** [comment]
The final version will be more like this
```json
{
"success": {
    "logtash-input-beats": "1.5.4",
    "logtash-input-file": "1.7.7",
   "logtash-codec-json": "1.8.7",
   },
 "failures": {
   "logtash-codec-XXXX": {
   "message": "....",
   "klass": "reference to the orignal object, I am not sure the format of theses."
   }
 }

**Comment by ph** [comment]
You can look at the final format at https://gist.github.com/ph/62b4624a4de8dc70ac933e3e19c83b20

**Comment by jordansissel** [comment]
Next steps:

* Update the docs sync to use @ph's tooling to get the correct plugin versions for a given branch of Logstash
* Capture the new per-plugin asciidoc from each plugin at the given version.

**Comment by ph** [comment]
@jordansissel So you can move forward in your changes https://gist.github.com/ph/9bc03a45d35851a9435e3c6d8377d281

**Comment by jordansissel** [comment]
Thank you!

**Comment by ph** [comment]
Have you make any progress here? Or I should go ahead and bump/publish all the plugins?

**Comment by jordansissel** [comment]
I haven't made progress. Been a lot of higher priority tasks this past two weeks (support, PRs, meetings) that prevented me from focusing on this.

**Comment by jordansissel** [comment]
https://github.com/elastic/docs-tools/pulls

**Comment by jordansissel** [comment]
https://github.com/elastic/docs-tools/pull/6
